apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: default
type: Opaque
data:
  # minio-user (base64)
  MINIO_ACCESS_KEY: bWluaW91c2Vy
  # minio-password-123 (base64)
  MINIO_SECRET_KEY: bWluaW8tcGFzc3dvcmQtMTIz

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: default
type: Opaque
data:
  # postgres (base64)
  postgres-user: cG9zdGdyZXM=
  # secure-password-123 (base64)
  postgres-password: c2VjdXJlLXBhc3N3b3JkLTEyMw==
